version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: movie-db-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "5433:5432" ]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped